version: '3'
services:
  nginx:
    build: ./nginx
    container_name: 'rm-nginx'
    tty: true
    ports:
      - "8080:80"
    volumes:
      - "./nginx/conf_d:/etc/nginx/conf.d"
      - "./nginx/static:/var/www/static"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - php

  php:
    build: ./php
    container_name: 'rm-php'
    tty: true
    volumes:
      - "../src:/opt/src"
    environment:
      TZ: "Asia/Tokyo"

  mysql:
    build: ./mysql
    container_name: 'rm-mysql'
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "q5EzPZr3"
      MYSQL_DATABASE: "rm"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "tK68bSQ5"
      BIND-ADDRESS: "0.0.0.0"
      TZ: 'Asia/Tokyo'
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf_d:/etc/mysql/conf.d"
      - "./mysql/mysql_init:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"